services:
  - type: web
    name: pet-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_USERNAME
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGODB_CLUSTER
        sync: false
      - key: MONGODB_DATABASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SECONDARY_URL
        value: https://furkids.vercel.app
      - key: CLIENT_URL
        value: https://pet-app-liart.vercel.app
    healthCheckPath: /health
    autoDeploy: true
